#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""supp_table.py — gera a TABELA SUPLEMENTAR do painel de concordancia de Tm por %GC
(item #11) a partir da MESMA fonte de verdade de gc_concordance.py (SETS + Tm).

Emite docs/supp_table_primer_panel.md com:
  - Tabela S (a): metadados por ensaio (organismo, alvo/GenBank, plataforma de
    desenho declarada no artigo, amplicon nt/%GC, max|dTm|, referencia + DOI);
  - Tabela S (b): sequencias dos primers (5'->3') com len, %GC, Tm LAMPrime,
    Tm BioPython e dTm por oligo.

Reproduzir:  python tools/supp_table.py
"""
import os, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("gc_concordance", os.path.join(HERE, "gc_concordance.py"))
G = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(G)

OUT = os.path.normpath(os.path.join(HERE, "..", "docs", "supp_table_primer_panel.md"))

# Metadados por ensaio (gene-alvo + acesso GenBank do alvo mapeado). Chave = SETS[].key
META = {
    "Pv_cox1":    ("mitochondrial cox1", "AY598035"),
    "Bb_cytb":    ("mitochondrial cytochrome b", "NC_009902"),
    "Eh_srehp":   ("SREHP (serine-rich protein)", "M80910.1"),
    "Pf_18S":     ("18S rRNA", "M19173"),
    "Cov2_S":     ("spike (S) CDS", "NC_045512.2:21563-25384"),
    "Cov2_ORF1ab":("ORF1ab (replicase)", "NC_045512.2:1-3000"),
    "Ec_malB":    ("malB / lamB", "J01648"),
    "Am_msp1b":   ("msp1beta (msp1b)", "M59845.1 (synthetic gBlocks)"),
    "Zikv_E":     ("envelope (E)", "KU501215"),
    "Xc_TIVSS":   ("Type IV secretion system gene", "NC_003919.1"),
    "Pa_ecfX":    ("ecfX (ECF sigma factor)", "CP025055.2"),
    "Mtb_IS6110": ("IS6110 insertion element", "X17348.1"),
    "Mk_rpoB":    ("rpoB", "NC_022663.1"),
}
OLIGO_ORDER = ("F3", "B3", "FIP", "BIP", "LF", "LB")


def build():
    R = G.rows()
    per = {}
    for r in R:
        per.setdefault(r["key"], []).append(r)

    # ordena por %GC do amplicon
    def agc(k):
        v = next((x["amplicon_gc"] for x in per[k] if x["amplicon_gc"]), "0")
        return float(v or 0)
    ordered = sorted(G.SETS, key=lambda S: agc(S["key"]))

    L = []
    L.append("# Supplementary Table S1 — LAMP primer panel for the independent Tm cross-check (#11)\n")
    L.append("> Auto-generated by `tools/supp_table.py` from the same source of truth as "
             "`tools/gc_concordance.py`. Do not edit by hand — re-run the script.\n")
    L.append("Independent validation of the LAMPrime melting-temperature engine against BioPython "
             "`Tm_NN` (nearest-neighbor table NN4 = SantaLucia & Hicks 2004; salt correction Owczarzy "
             "2004) over published LAMP primer sets **designed with other tools** (Eiken PrimerExplorer "
             "V3/V4/V5 or NEB — none by LAMPrime). Conditions: Na+ 50 mM, Mg2+ 8 mM, dNTP 1.4 mM, "
             "effective oligo 12.5 nM. Every set was QC-mapped onto its GenBank target (the primers form "
             "a compact ~180-240 nt LAMP amplicon); the reported GC is that of the F3-B3 amplicon. All "
             "primer sequences are verbatim from the cited sources.\n")

    # ---- Table S1a: metadata ----
    L.append("## Table S1a — Assay metadata and design platform\n")
    L.append("| # | Assay | Organism | Target (gene) | GenBank | Design platform | Amplicon (nt) | Amplicon GC (%) | max \\|ΔTm\\| (°C) | Reference (DOI) |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for i, S in enumerate(ordered, 1):
        rs = per[S["key"]]
        gene, acc = META.get(S["key"], ("", ""))
        gc = next((x["amplicon_gc"] for x in rs if x["amplicon_gc"]), "?")
        tgt = G._readfa(S["target"])
        alen, _ = G.amplicon_gc(S["P"], tgt)
        ds = [abs(float(x["d"])) for x in rs if x["d"]]
        mx = ("%.3f" % max(ds)) if ds else "n/a"
        doi = S["doi"]
        L.append("| %d | %s | *%s* | %s | %s | %s | %s | %s | %s | %s · [%s](https://doi.org/%s) |"
                 % (i, S["name"], S["organism"], gene, acc, S["tool"],
                    (str(alen) if alen else "?"), gc, mx, S["ref"], doi, doi))

    # ---- Table S1b: primer sequences ----
    L.append("\n## Table S1b — Primer sequences and per-oligo Tm\n")
    L.append("Tm(L) = LAMPrime (`concordance.tm`); Tm(B) = BioPython `Tm_NN` (NN4, Owczarzy 2004); "
             "ΔTm = Tm(L) − Tm(B).\n")
    L.append("| Assay | Oligo | Sequence (5′→3′) | Len | GC (%) | Tm(L) | Tm(B) | ΔTm |")
    L.append("|---|---|---|---|---|---|---|---|")
    for S in ordered:
        rmap = {r["oligo"]: r for r in per[S["key"]]}
        first = True
        for k in OLIGO_ORDER:
            if k not in rmap:
                continue
            r = rmap[k]
            L.append("| %s | %s | `%s` | %s | %s | %s | %s | %s |"
                     % (S["name"] if first else "", k, S["P"][k], r["length"], r["gc"],
                        r["tm_lamprime"], r["tm_bio5"] or "—", r["d"] or "—"))
            first = False

    # ---- footer stats ----
    alld = [abs(float(x["d"])) for x in R if x["d"]]
    if alld:
        L.append("\n**Panel totals:** %d assays · %d oligos · GC %.0f–%.0f%% · "
                 "mean |ΔTm| %.3f °C · median %.3f °C · max %.3f °C."
                 % (len(G.SETS), len(alld), min(float(x["amplicon_gc"]) for x in R if x["amplicon_gc"]),
                    max(float(x["amplicon_gc"]) for x in R if x["amplicon_gc"]),
                    sum(alld)/len(alld), sorted(alld)[len(alld)//2], max(alld)))
    return "\n".join(L) + "\n"


def main():
    txt = build()
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(txt)
    print("saved", OUT)
    print("  %d bytes" % len(txt))


if __name__ == "__main__":
    main()
